### ISSUE TITLE
work locations

### ISSUE THREAD

**Issue by eroux** [buda-base/embedded-reader-import#1]
There's a need for adding work locations in the collections (for works for which we have no outline). This is already theoretically possible but hasn't really been tested. The first step is to add these four things to the tsv files:
- start volume (sv)
- end volume (ev)
- start page (sp)
- end page (ep)

I propose something like:

```
W123(sp,ep,sv,ev) title
```

where `sv` is optional (defaults to `1`) and `ev` is optional too (defaults to `ev`). Would that be ok?

**Comment by xristy** [comment]
small correction: `ev` defaults to `sv`; otherwise, seems reasonable. So for each of the `:workLinkTo` you'll replace with `:workLocation`?

**Comment by eroux** [comment]
I can't remember the details but I remember we considered this in rfc02

**Comment by eroux** [comment]
@ngawangtrinley look at [test.tsv](https://github.com/buda-base/embedded-reader-import/blob/master/tests/test.tsv) for an example (be careful, there should be no space)
