### ISSUE TITLE
Work with new id in embedded reader doesnt showing the scanned image.

### ISSUE THREAD

**Issue by jeehuajian** [buda-base/embedded-reader-import#28]
1) Embedded reader showing works with new id start with letter "M". Not showing the scanned image.
![image](https://user-images.githubusercontent.com/42564256/89144388-37fbcb00-d580-11ea-9017-9c11a8c46df3.png)

2) The input of the embedded reader.
![image](https://user-images.githubusercontent.com/42564256/89144499-8c9f4600-d580-11ea-8140-3a37697a2c0c.png)

**Comment by eroux** [comment]
I think I've fixed it... is there a URL where I can try your initial bug?

**Comment by jeehuajian** [comment]
Problem fixed. thank you.
