### ISSUE TITLE
BDRC and BUDA Logos in embedded reader

### ISSUE THREAD

**Issue by jeehuajian** [buda-base/embedded-reader-import#29]
BDRC and Buda logos in embedded reader isnt look so confortable. Will it be ok if remove the logos?

![image](https://user-images.githubusercontent.com/42564256/89144968-dd636e80-d581-11ea-8980-438ba2fb6343.png)

**Comment by eroux** [comment]
indeed yes, tracked on https://github.com/buda-base/public-digital-library/issues/179 , it should be fixed today

**Comment by eroux** [comment]
@jeehuajian we just deployed a new version, does it work for you?
