### ISSUE TITLE
The Text ID taken from new BDRC WEb not working in the Window

### ISSUE THREAD

**Issue by tadhondup** [buda-base/embedded-reader-import#5]
One example. W5062_0004 Line 9 in Shechen. Click here [Shechen](https://github.com/buda-base/embedded-reader-import/blob/master/input/W1ERI0009.tsv#L10)

I put only one example here. But all others Work numbers taken from new BDRC Website are same, not working. Please Check them.

**Comment by eroux** [comment]
thanks, tracked on https://github.com/buda-base/buda-iiif-presentation/issues/53
