### ISSUE TITLE
Recently can not find out text from collections as before in new website

### ISSUE THREAD

**Issue by tadhondup** [buda-base/embedded-reader-import#8]
We can find a single text from a big collections in our new website before but recently its not working. If I find a text with its title, it comes with whole collection. Please check. For examole. 
![image](https://user-images.githubusercontent.com/28945342/64498388-d5a23800-d2e6-11e9-951a-eb28e2556715.png)

**Comment by eroux** [comment]
thanks, follow up on https://github.com/buda-base/buda-iiif-presentation/issues/66
